### ISSUE TITLE
firmware updating

### ISSUE THREAD

**Issue by magichowl** [neoreeps/surface-pro-3#1]
I'm current using a laptop with Ubuntu and Vmware Windows, so I agree with you for a single OS.

For the case of surface pro 3, someone says

```
 At the very least you'll need Windows if you ever want firmware updates
```

How do you think?

**Comment by neoreeps** [comment]
Yeah, if you want firmware updates, you'll need to either create a bootable windows copy (a couple methods to do this) or dual boot.  I don't worry about it; if everything works, why update it?

Hopefully somebody will write a fw tool for linux ... then this won't be an issue
