### ISSUE TITLE
ur not keep efi partition？

### ISSUE THREAD

**Issue by magichowl** [neoreeps/surface-pro-3#10]
I kept efi partition and installed ubuntu 15.10 64bit successfully but surface keep on repairing system after boot. even I disabled secure boot and tpm I can't boot ubuntu.

**Comment by magichowl** [comment]
In the readme, you said to erase the disk. is it ok to delete efi partition?

**Comment by magichowl** [comment]
I delete efi partition and recreate one of my own. Then I encounter the problem of loop uefi. The problem now is I can set root and boot ubuntu, but the next time I still have to insert ubuntu pendriver to set root and boot, or else enter the loop uefi. I'm ignoring it and try patch system first. Do you have any suggestions?

**Comment by neoreeps** [comment]
After you boot, run grub-install /dev/sda ... (NOT /dev/sda1) ... good luck, i hope there wasnt a firmware change that b0rks grub ...

**Comment by magichowl** [comment]
my devices are  the follows.
usb driver is /dev/sda
ssd is /dev/nvme0n1
where efi is /dev/nvme0n1p1
and system "/" is /dev/nvme0n1p2

```
sspan@sspan-SP4:~$ grub-install /dev/nvme0n1
Installing for x86_64-efi platform.
grub-install: warning: disk does not exist, so falling back to partition device /dev/nvme0n1p1.
grub-install: warning: disk does not exist, so falling back to partition device /dev/nvme0n1p1.
grub-install: warning: disk does not exist, so falling back to partition device /dev/nvme0n1p1.
grub-install: error: disk `hostdisk//dev/nvme0n1p1' not found.
```

When I use command with sudo, installation succeeded.
Unfortunately, loop uefi not solved

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?

```
Disk /dev/nvme0n1: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 7F4B27D3-0A94-4EC7-9423-90A6261F3544

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      2048    499711    497664   243M EFI System
/dev/nvme0n1p2    499712 140795903 140296192  66.9G Linux filesystem
/dev/nvme0n1p4 252596224 498354175 245757952 117.2G Microsoft basic data
/dev/nvme0n1p5 498356224 500117503   1761280   860M Windows recovery environment
/dev/nvme0n1p6 140795904 240795647  99999744  47.7G Linux filesystem
/dev/nvme0n1p7 240795648 252596223  11800576   5.6G Linux swap

Partition table entries are not in disk order.
```

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?
```
Disk /dev/nvme0n1: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 7F4B27D3-0A94-4EC7-9423-90A6261F3544

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      2048    499711    497664   243M EFI System
/dev/nvme0n1p2    499712 140795903 140296192  66.9G Linux filesystem
/dev/nvme0n1p4 252596224 498354175 245757952 117.2G Microsoft basic data
/dev/nvme0n1p5 498356224 500117503   1761280   860M Windows recovery environment
/dev/nvme0n1p6 140795904 240795647  99999744  47.7G Linux filesystem
/dev/nvme0n1p7 240795648 252596223  11800576   5.6G Linux swap

Partition table entries are not in disk order.
```

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?
```
Disk /dev/nvme0n1: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 7F4B27D3-0A94-4EC7-9423-90A6261F3544

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      2048    499711    497664   243M EFI System
/dev/nvme0n1p2    499712 140795903 140296192  66.9G Linux filesystem
/dev/nvme0n1p4 252596224 498354175 245757952 117.2G Microsoft basic data
/dev/nvme0n1p5 498356224 500117503   1761280   860M Windows recovery environment
/dev/nvme0n1p6 140795904 240795647  99999744  47.7G Linux filesystem
/dev/nvme0n1p7 240795648 252596223  11800576   5.6G Linux swap

Partition table entries are not in disk order.
```

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?
```
Disk /dev/nvme0n1: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 7F4B27D3-0A94-4EC7-9423-90A6261F3544

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      2048    499711    497664   243M EFI System
/dev/nvme0n1p2    499712 140795903 140296192  66.9G Linux filesystem
/dev/nvme0n1p4 252596224 498354175 245757952 117.2G Microsoft basic data
/dev/nvme0n1p5 498356224 500117503   1761280   860M Windows recovery environment
/dev/nvme0n1p6 140795904 240795647  99999744  47.7G Linux filesystem
/dev/nvme0n1p7 240795648 252596223  11800576   5.6G Linux swap

Partition table entries are not in disk order.
```

**Comment by magichowl** [comment]
Weirdly, I can't even see my SSD in GParted even if its partitions can be mounted or alreay mounted, is it related to installation process where boot loader is kept in /dev/nvme, which should be changed in /dev/mvme0n1 (256G SSD) ?
```
Disk /dev/nvme0n1: 238.5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 7F4B27D3-0A94-4EC7-9423-90A6261F3544

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      2048    499711    497664   243M EFI System
/dev/nvme0n1p2    499712 140795903 140296192  66.9G Linux filesystem
/dev/nvme0n1p4 252596224 498354175 245757952 117.2G Microsoft basic data
/dev/nvme0n1p5 498356224 500117503   1761280   860M Windows recovery environment
/dev/nvme0n1p6 140795904 240795647  99999744  47.7G Linux filesystem
/dev/nvme0n1p7 240795648 252596223  11800576   5.6G Linux swap

Partition table entries are not in disk order.
```

**Comment by magichowl** [comment]
neither boot-repair nor reinstall grub  works. see http:/paste.ubuntu.com/14474591

**Comment by magichowl** [comment]
upgraded gparted can recognize nvme ssd 
![screenshot from 2016-01-12 17-24-52](https://cloud.githubusercontent.com/assets/1439061/12265898/de097a28-b97a-11e5-83b8-749b3bba4401.png)

Follow someone's opinion to uncheck secureboot in advanced option of boot-repair, now booting computer will encounter "Secureboot violation" error.

**Comment by magichowl** [comment]
break through by using boot-repair without secureboot option, and disable secureboot **after first start computer**, I managed to grub.
However, in advance options, kernel 4.3 can't be started (see following pic), while 4.2.0-16 and 4.2.0-23 boot normally.

![qq 20160113100024](https://cloud.githubusercontent.com/assets/1439061/12282904/ffef63b6-b9dc-11e5-8296-881044dda3fd.jpg)

**Comment by magichowl** [comment]
Sorry for bothering you a lot. Hope you don't mind.
details of errors are:

```
ACPI:SCI (ACPI GSI 9) not registered
sunrisepoint-pin ctrl INT344B:00: failed to request interrup
sunrisepoint-pin ctrl probe of INT344B:00 failedwitherror-38
[drm:intel_dp_aux_ch [i915]] *ERROR* dp aux hw did not signal time out (has irq:1)!
[drm:intel_dp_aux_ch [i915]] *ERROR* dp_aux_ch not done status 0xad40001f
[drm:intel_dp_start_link_train [i915]] *ERROR* fail to enable link training
[drm:intel_dp_complete_link_train [i915]] *ERROR* fail to start channel equalization
could not open moddep file '/lib/modules/4.3.0-reeps/modules.dep.bin'
failed to lookup alias 'lp': function not implemented
failed to lookup alias  'ppdev': function not implemented
failed to lookup alias 'parport_pc': function not implemented
Failed to mount /boot/efi
FAT-fs IO charset iso8859-1 not found
```

**Comment by magichowl** [comment]
I use the wily_surface.patch in kernel 4.2, and the typecover works. Thanks.  
pen, touchscreen, side buttons, camera not work. 
suspend can't be waken, either.  Too pain to work outside.
