### ISSUE TITLE
Update install instuctions

### ISSUE THREAD

**Issue by mkassner** [neoreeps/surface-pro-3#12]
First off thanks for this awesome project in collecting the patches. I d like to suggest a few edits in the instructions:
- Don't use 15.10 it fails at installing grup properly on the SP4. Instead use 15.04 and update to 15.10 once installed.
- When installing the Kernel don't follow up with the grub command. Its not necessary and breaks grub on the SP4.

**Comment by neoreeps** [comment]
added caveat to README.  Thanks.
