### ISSUE TITLE
Type Cover 3 not working even in 4.2.0

### ISSUE THREAD

**Issue by mraufrufi** [neoreeps/surface-pro-3#3]
my type cover is 07e2 , tried your build but still type cover is not working.

**Comment by neoreeps** [comment]
Please send the output of lspci and lsusb and i'll add yours to the patch.  My typecover is an original and I believe they iterated a couple times on the hardware.

**Comment by neoreeps** [comment]
Try the latest version of patch or pre-built kernels from README.
