### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by 1beb** [neoreeps/surface-pro-3#6]
Just wanted to drop a thanks for putting this together. I'm using your 4.3 kernel right now and everything seems to be working swimmingly. Even the battery! Which is a great jump ahead from previously.

**Comment by neoreeps** [comment]
Thanks for the note. im waiting on s Surface book from work so I can do the same there.

**Comment by 1beb** [comment]
Jealous! It's way to expensive in Canada right now. Going to wait until the US/CAD ratio comes back into a reasonable zone before I splurge on a surface book. Probably won't be until next generation though, sadly!
