### ISSUE TITLE
Boot options

### ISSUE THREAD

**Issue by jcontonio** [neoreeps/surface-pro-3#7]
Hey there, thanks for this. I've checked out the repo and ran `clone release`. Now what do I do? I've tried rebooting into the Grub menu and I don't see your kernel listed. I see 4.3.0-040300-generic and 4.2.0-22-generic.

**Comment by 1beb** [comment]
If you're using ubuntu, downloading the pre-build debs and installing them is really straight forward: 

```
sudo dpkg -i linux-*
```

**Comment by jcontonio** [comment]
Hey great! Thank you.
