### ISSUE TITLE
Is kernel 4.3 supported by vmware workstation 12 pro?

### ISSUE THREAD

**Issue by magichowl** [neoreeps/surface-pro-3#8]
AFAIK, ubuntu 15.10 (default kernel is 4.2?) can run vmware workstation12 Pro. 
Do you know kernel 4.3 is OK? Or VMworkstation can be patched? Or use other vitural mechine?

**Comment by 1beb** [comment]
I'm going to hazard a guess and go with no. It looks like someone else has already complained about this. In Issue #5. A little web reading suggests problems with VBOX and custom kernels akin to this repo.
